import {
  congDungApi,
  danhMucApi,
  dangSanPhamApi,
  mauSacApi,
  thanhPhanApi,
  thuongHieuApi,
} from '@/api/thuocTinhApi'

export const ATTRIBUTE_TYPES = {
  'thuong-hieu': {
    key: 'thuong-hieu',
    title: 'Quản lý Thương hiệu',
    subtitle: 'Quản lý danh sách thương hiệu sản phẩm chống nắng tại cửa hàng',
    listTitle: 'Danh sách thương hiệu',
    api: thuongHieuApi,
    hasStatus: true,
    searchPlaceholder: 'Nhập tên thương hiệu, mã...',
    columns: [
      { key: 'ma', label: 'Mã', primary: true },
      { key: 'ten', label: 'Tên thương hiệu' },
      { key: 'xuatXu', label: 'Xuất xứ' },
    ],
    fields: [
      { key: 'ma', label: 'Mã thương hiệu', required: true, placeholder: 'VD: TH001' },
      { key: 'ten', label: 'Tên thương hiệu', required: true, placeholder: 'VD: Anessa, La Roche-Posay...' },
      { key: 'xuatXu', label: 'Xuất xứ', placeholder: 'VD: Nhật Bản, Pháp...' },
    ],
  },
  'danh-muc': {
    key: 'danh-muc',
    title: 'Quản lý Danh mục',
    subtitle: 'Quản lý danh mục sản phẩm chống nắng',
    listTitle: 'Danh sách danh mục',
    api: danhMucApi,
    hasStatus: true,
    searchPlaceholder: 'Nhập tên danh mục, mã...',
    columns: [
      { key: 'ma', label: 'Mã', primary: true },
      { key: 'ten', label: 'Tên danh mục' },
      { key: 'moTa', label: 'Mô tả' },
    ],
    fields: [
      { key: 'ma', label: 'Mã danh mục', required: true, placeholder: 'VD: DM001' },
      { key: 'ten', label: 'Tên danh mục', required: true, placeholder: 'VD: Kem chống nắng' },
      { key: 'moTa', label: 'Mô tả', type: 'textarea', placeholder: 'Mô tả ngắn...' },
    ],
  },
  'dang-san-pham': {
    key: 'dang-san-pham',
    title: 'Quản lý Dạng sản phẩm',
    subtitle: 'Quản lý các dạng bào chế: kem, gel, xịt, sữa...',
    listTitle: 'Danh sách dạng sản phẩm',
    api: dangSanPhamApi,
    hasStatus: true,
    searchPlaceholder: 'Nhập tên dạng sản phẩm, mã...',
    columns: [
      { key: 'ma', label: 'Mã', primary: true },
      { key: 'ten', label: 'Tên dạng' },
      { key: 'moTa', label: 'Mô tả' },
    ],
    fields: [
      { key: 'ma', label: 'Mã dạng', required: true, placeholder: 'VD: DS001' },
      { key: 'ten', label: 'Tên dạng', required: true, placeholder: 'VD: Kem, Gel, Xịt' },
      { key: 'moTa', label: 'Mô tả', type: 'textarea' },
    ],
  },
  'mau-sac': {
    key: 'mau-sac',
    title: 'Quản lý Màu sắc',
    subtitle: 'Quản lý danh sách các tùy chọn màu sắc sản phẩm',
    listTitle: 'Danh sách màu sắc',
    api: mauSacApi,
    hasStatus: true,
    searchPlaceholder: 'Nhập tên màu...',
    columns: [
      { key: 'ten', label: 'Tên màu', bold: true },
      { key: 'ma', label: 'Mã' },
      { key: 'maHex', label: 'Mã màu', type: 'color' },
    ],
    fields: [
      { key: 'ma', label: 'Mã màu sắc', required: true, placeholder: 'VD: MS001' },
      { key: 'ten', label: 'Tên màu', required: true, placeholder: 'VD: Hồng nhạt, Be...' },
      { key: 'maHex', label: 'Mã màu (Hex)', required: true, type: 'color', default: '#000000' },
    ],
  },
  'cong-dung': {
    key: 'cong-dung',
    title: 'Quản lý Công dụng',
    subtitle: 'Quản lý công dụng sản phẩm chống nắng',
    listTitle: 'Danh sách công dụng',
    api: congDungApi,
    hasStatus: true,
    searchPlaceholder: 'Nhập tên công dụng, mã...',
    columns: [
      { key: 'ma', label: 'Mã', primary: true },
      { key: 'ten', label: 'Tên công dụng' },
      { key: 'moTa', label: 'Mô tả' },
    ],
    fields: [
      { key: 'ma', label: 'Mã công dụng', required: true },
      { key: 'ten', label: 'Tên công dụng', required: true },
      { key: 'moTa', label: 'Mô tả', type: 'textarea' },
    ],
  },
  'thanh-phan': {
    key: 'thanh-phan',
    title: 'Quản lý Thành phần',
    subtitle: 'Quản lý thành phần hoạt chất trong sản phẩm',
    listTitle: 'Danh sách thành phần',
    api: thanhPhanApi,
    hasStatus: true,
    searchPlaceholder: 'Nhập tên thành phần, mã...',
    columns: [
      { key: 'ma', label: 'Mã', primary: true },
      { key: 'ten', label: 'Tên thành phần' },
      { key: 'moTa', label: 'Mô tả' },
    ],
    fields: [
      { key: 'ma', label: 'Mã thành phần', required: true },
      { key: 'ten', label: 'Tên thành phần', required: true },
      { key: 'moTa', label: 'Mô tả', type: 'textarea' },
    ],
  },
}
